---
name: Publish to GitHub Pages

on:
  schedule:
    - cron: '3 */4 * * *' # Every four hours.
  push:
    branches:
      - forestry

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fabacab/jekyll-builder-for-github-pages-action@builder-3.8
      with:
        secret_gh_pages_api_token: ${{ secrets.GH_PAGES_TOKEN }}
        jekyll_build_opts: --future
