name: Publish to GitHub Pages

on:
  schedule:
    - cron: '3 */2 * * *' # Every two hours.
  push:
    branches:
      - forestry

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: meitar/action-build-deploy-ghpages@master
      with:
        github_token: ${{ github.token }}
        gh_pages_token: ${{ secrets.GH_PAGES_TOKEN }}
        gh_pages_branch: master
        jekyll_build_opts: --future
